### ISSUE TITLE
Link to Community Sheet Repo

### ISSUE THREAD

**Issue by acsearles** [Roll20/beacon-docs#10]
Quick start sheet and Example Sheet need links to the Community Sheet Repo where the sheet developers can download them.

- Community Sheet Repo - https://github.com/Roll20/roll20-beacon-sheets
- Quick Start Sheet - https://github.com/Roll20/roll20-beacon-sheets/tree/main/sheets/quickstart-example-sheet
- Advanced Example Sheet - sheets/advanced-example-sheet

**Comment by Davidakanmu** [comment]
Fixed
