### ISSUE TITLE
Add a call out for the Closed Beta

### ISSUE THREAD

**Issue by acsearles** [Roll20/beacon-docs#11]
At the top of the intro page, we need a call out box that draws the readers attention that this is currently in closed beta. 

This is the form that someone should fill out in order to get access to the closed beta.
https://forms.gle/XXnj1SbfmYnUq8Hu9

Also, this document talks about the release of the closed beta.
https://docs.google.com/document/d/1lVXp2TKb5gof-6hXvjWgQ7Zo09LZlorBoyjv5un8IeU/edit?usp=sharing

**Comment by Davidakanmu** [comment]
Fixed
